### PR TITLE
[Mac] Allow Ctrl+Shift+i to display the Property Button's menu.

### PR DESCRIPTION
**Pull request by CartBlanche**

### CODE REVIEW

**Comment by CartBlanche** [comment]
Not particularly happy about the hoops to jump through to trigger the pop-up, but this appears to work. If you know of a more elegant solution, shout out!

**Comment by chkn** [comment]
Doesn't look too bad to me

**Comment by CartBlanche** [comment]
@vancura Do you have a suggestion other than Ctrl+Space?

**Comment by sevoku** [comment]
There is no shortcut for this on a Mac and we should not add it just for proppy and nowhere else. Also CTRL+SPACE is a Windows specific shortcut.

With VO there is VO+SHIFT+M to open a context menu of the current element. For this to work you might need to implement [accessibilityPerformShowMenu](https://developer.apple.com/documentation/appkit/nsaccessibilityprotocol/1532774-accessibilityperformshowmenu)

**Comment by vancura** [comment]
@CartBlanche We have an ongoing conversation in our team room, I'll paste the results here when we have a solution.

**Comment by vancura** [comment]
@CartBlanche We don't have a solution :) Please don't use that shortcut.

**Pull request merged**
