### PR TITLE
Multi-target net472 and net6.0-macos

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Review by netonjm — APPROVED** [review]

**Comment by Therzok** [comment]
Breaks CI because CI uses mono/.netframework, ugh.

**Comment by Therzok** [comment]
@mcumming are there any plans to setup CI for net6.0?

**Comment by mcumming** [comment]
Hadn't had a need yet, can surely look into it.

**Comment by sandyarmstrong** [comment]
I restored this branch because VSMac references it as a submodule, and deleting the branch broke our builds.

We can delete it after we update to latest `main` of this repo in relevant VSMac branches.

**Comment by Therzok** [comment]
Ooops, sorry for that!

**Pull request closed without merging**
