### PR TITLE
Initial Color Editor Control using NSColorWell.

### PR DESCRIPTION
**Pull request by CartBlanche**
screen shot 2017-05-04 at 16 29 13

### CODE REVIEW

**Comment by alanmcgovern** [comment]
This control is already implemented in our codebase so we should re-use it. We have a much better popover based impl there which we can transplant into this repo!

**Comment by CartBlanche** [comment]
@alanmcgovern was it using NSColorWell or something else?

**Comment by CartBlanche** [comment]
from @viniciusjarina - https://github.com/xamarin/md-addins/blob/master/Xamarin.Designer.iOS/MonoTouch.Design.Client.Mac/NativePropertyEditing/ColorPropertyEntry.cs#L505

**Comment by ermau** [comment]
This is such a complex piece, I'm going to close it for now until we see what we're getting from design as hopefully we can do all our changes at once. Furthermore, we want our controls to always deal with the shared value type, which in this case would be the System.Drawing colors types, not the native Cocoa ones.

**Pull request closed without merging**
