### PR TITLE
High Contrast Icons

### PR DESCRIPTION
**Pull request by vancura**
High contrast versions of all icons.

MonoDevelop: https://github.com/mono/monodevelop/pull/9510
md-addins: https://github.com/xamarin/md-addins/pull/6154
designer: https://github.com/xamarin/designer/pull/2657
vsmac-xamarin-extensions: https://github.com/xamarin/vsmac-xamarin-extensions/pull/571
android-sdk-installer: https://github.com/xamarin/android-sdk-installer/pull/366

### CODE REVIEW

**Comment by vancura** [comment]
This is done.

**Comment by vancura** [comment]
@sevoku How to update the other repo? Is it enough just to update submodule refs?

**Comment by garuma** [comment]
@monojenkins backport to d16-5

**Comment by garuma** [comment]
@monojenkins backport to d16-4

**Comment by garuma** [comment]
@sevoku @vancura I don't think the new icon scheme will work until either our [HostResourceProvider](https://github.com/xamarin/Xamarin.PropertyEditing/blob/51d031eb955fc6155e91d55e0acab7bb31ef6faa/Xamarin.PropertyEditing.Mac/HostResourceProvider.cs#L40-L54) or [your provider extension](https://github.com/mono/monodevelop/blob/master/main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/MonoDevelopHostResourceProvider.cs) implements the support (or proxies it to Xwt).

**Pull request merged**
