### PR TITLE
[Mac] Autoresizing implementation

### PR DESCRIPTION
**Pull request by CartBlanche**
Screen Shot 2019-10-10 at 20 40 54

### CODE REVIEW

**Comment by CartBlanche** [comment]
@viniciusjarina & @chkn This is the port of the Autoresizing control into proppy. Could you please look over it and the video I posted on Slack in #proppy (https://xamarinhq.slack.com/archives/C5GBTFXL0/p1568909239055500). It Supports theming and keyboard navigation (Left and Right arrows to cycle through the flags). With theming we need to decide what the actual colour scheme will be between dark and light, but that should be easily changed once we finalise what that will actually be.

**Comment by ermau** [comment]
@CartBlanche Theming is here https://github.com/xamarin/Xamarin.PropertyEditing/issues/616#issuecomment-528410763

**Comment by ermau** [comment]
You'll want to rebase this and use the rectangle sizing methodology now present in the view model as it is more correct.

**Comment by CartBlanche** [comment]
@ermau just to be clear, you are referring to `VM.GetPreviewElementRectangle`?

**Comment by ermau** [comment]
@CartBlanche Correct.

**Comment by CartBlanche** [comment]
I made it a vertical alignment as it really is better aesthetically than the horizontal one that doesn't support resizing. We can always revisit the alignment, should Forms be needed.

**Pull request closed without merging**
