### PR TITLE
Convert from xammac library proj

### PR DESCRIPTION
**Pull request by alanmcgovern**

### CODE REVIEW

**Comment by alanmcgovern** [comment]
This should be rebased/mergeg after the resx movement PR merges. There'll be fewer conflicts then!

**Comment by CartBlanche** [comment]
@alanmcgovern I rebased and pushed, and on the build server everything appears to be fine, but locally tests are failing. Are you seeing that behaviour locally?

**Comment by CartBlanche** [comment]
Looks like it may be VSM related.

**Pull request merged**
