### PR TITLE
Adding Azure DevOps YAML build file

### PR DESCRIPTION
**Pull request by mcumming**
- Build master, release branches commit and PR's
- Processes translations from localization pipeline
- Update README to point at new pipeline
- Added github action to auto-create PR when trnaslations are pushed on `loc` branch.

Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1052929

### CODE REVIEW

**Comment by CartBlanche** [comment]
@mcumming So is this change to automate pulling in the translations? 

Are there now 2 builds going on? One for translation over on `https://dev.azure.com/xamarin/public/_build?definitionId=50` and the other on  `https://devdiv.visualstudio.com/DevDiv/_build/latest?definitionId=5330` or does this means we only have 1 build happening now?

I'm just trying to understand what we are trying to achieve as I have no context for this PR.

**Comment by mcumming** [comment]
> @mcumming So is this change to automate pulling in the translations?
> 
> Are there now 2 builds going on? One for translation over on `https://dev.azure.com/xamarin/public/_build?definitionId=50` and the other on `https://devdiv.visualstudio.com/DevDiv/_build/latest?definitionId=5330` or does this means we only have 1 build happening now?
> 
> I'm just trying to understand what we are trying to achieve as I have no context for this PR.

This will replace the existing build definition which is private with one that is publicly accessible, and includes translation processing.

**Comment by CartBlanche** [comment]
@mcumming Any ideas about the failing build and the Mac build which hasn't finished/updated for about 5 hours now?

**Comment by mcumming** [comment]
> @mcumming Any ideas about the failing build?

Resolved.

**Pull request merged**
